Add `RateLimit` exception to raise when we hit the limit on our requests
mavenlink/hubspot-ruby pull request #1
Opened 2022-03-05 00:42 UTC by chan-song-sy

Add new `RateLimitError` exception to the exceptions class. Raise `RateLimitError` if the error type is `RATE_LIMIT` (according to HubSpot API https://legacydocs.hubspot.com/docs/faq/working-within-the-hubspot-api-rate-limits). If the error is type is not `RATE_LIMIT` we fallback to what it did originally which is raised a `RequestError`.

2022-03-07 16:46 UTC, matthewdeol approved these changes

2022-03-07 18:39 UTC, b6b requested changes
Looks good to me but we should try update the specs to cover this new behavior

2022-03-07 18:39 UTC, b6b commented on lib/hubspot/connection.rb
> +        if response[:errorType] == "RATE_LIMIT"
It may be good to make this a `case` so that it is a bit cleaner to expand on in the future. I think it would also be good to move "RATE_LIMIT" into a constant.

2022-03-07 22:26 UTC, chan-song-sy commented on lib/hubspot/connection.rb
> +        if response[:errorType] == "RATE_LIMIT"
Will make the change for `RATE_LIMIT` as a constant. When you say make it a `case` is that making it a switch statement?

2022-03-07 22:50 UTC, b6b commented on lib/hubspot/connection.rb
> +        if response[:errorType] == "RATE_LIMIT"
Yeah, case/switch.

2022-03-07 23:56 UTC, chan-song-sy commented on lib/hubspot/connection.rb
> +        if response[:errorType] == "RATE_LIMIT"
Sorry just went Java mode 😵  thought it was the same in RoR lol. Okay requested changes made!

2022-03-08 00:26 UTC, b6b commented on spec/lib/hubspot/connection_spec.rb
> +          path = "/some/path"
It's better to define these variables within a `let` outside of the test. Since this particular value is also the same in the context below it can be shared at a higher level. 

Also the request stubbing can be pulled out to a `before` in each context as well to better separate test setup and assertions.

2022-03-08 00:26 UTC, b6b commented on spec/lib/hubspot/connection_spec.rb
> +
👮‍♂️  extra newline

Also ditto on pulling test setup outside of the `it`.

2022-03-08 01:31 UTC, b6b approved these changes
LGTM 👍  Thanks for the changes

2022-03-08 18:55 UTC, merged